# Generated by Django 5.2.6 on 2026-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('License Expiry', 'License Expiry'), ('Document Expiry', 'Document Expiry'), ('Mileage Deviation', 'Mileage Deviation'), ('Depot Overdue', 'Depot Return Overdue')], max_length=30)),
                ('reference_entity', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
