# Generated by Django 5.2.6 on 2026-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('truck_type', models.CharField(blank=True, default='', max_length=20)),
                ('rate_type', models.CharField(choices=[('Flat', 'Flat Rate'), ('Per KM', 'Per KM'), ('Per Ton', 'Per Ton'), ('Per Ton-KM', 'Per Ton-KM')], default='Flat', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'freight_rates',
                'ordering': ['from_city', 'to_city'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('party_type', models.CharField(choices=[('Consignor', 'Consignor (Sender)'), ('Consignee', 'Consignee (Receiver)'), ('Transporter', 'Transporter'), ('Broker', 'Broker / Agent')], default='Consignor', max_length=20)),
                ('gstin', models.CharField(blank=True, default='', help_text='GST Identification Number', max_length=15)),
                ('pan', models.CharField(blank=True, default='', help_text='PAN Number', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('contact_person', models.CharField(blank=True, default='', max_length=150)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('mobile2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_days', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance (positive = receivable, negative = payable)', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parties',
                'ordering': ['name'],
            },
        ),
    ]
