# Generated by Django 5.2.6 on 2026-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='tds_applicable',
            field=models.BooleanField(default=False, help_text='Is TDS applicable on payments to this party?'),
        ),
        migrations.AddField(
            model_name='party',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TDS rate in %', max_digits=5),
        ),
        migrations.AddField(
            model_name='party',
            name='tds_section',
            field=models.CharField(blank=True, default='194C', help_text='TDS section (e.g. 194C for transporters)', max_length=20),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('destination', models.CharField(db_index=True, max_length=100)),
                ('standard_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standard_driver_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Fixed driver allowance/batta for this route (INR)', max_digits=10)),
                ('estimated_tolls', models.DecimalField(decimal_places=2, default=0, help_text='Estimated toll charges for this route (INR)', max_digits=10)),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated total fuel cost at average mileage (INR)', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['source', 'destination'],
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
