# Generated by Django 5.2.6 on 2026-07-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('trips', '0003_trip_average_kmpl_trip_departure_km_trip_run_km'),
        ('vehicles', '0004_vehicle_account_reference_vehicle_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('Advance', 'Driver Advance'), ('Balance', 'Balance Payment'), ('Diesel Advance', 'Diesel Advance'), ('Other', 'Other')], default='Advance', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('GPay/UPI', 'GPay/UPI'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date'],
            },
        ),
    ]
