# Generated by Django 5.2.6 on 2026-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='pump_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
