# Generated by Django 5.2.6 on 2026-07-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('finance', '0003_fuellog_pump_name'),
        ('parties', '0002_party_bank_account_number_party_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parties.party'),
        ),
    ]
