# Generated by Django 5.2.6 on 2026-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(blank=True, default='', max_length=20)),
                ('license_expiry_date', models.DateField()),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Safety score out of 100', max_digits=5)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Off Duty', 'Off Duty'), ('Suspended', 'Suspended')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['name'],
            },
        ),
    ]
