# Generated by Django 5.2.6 on 2026-07-12 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Mini', 'Mini'), ('Bus', 'Bus'), ('Other', 'Other')], default='Van', max_length=20)),
                ('max_load_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RC', 'RC Book'), ('Insurance', 'Insurance'), ('PUC', 'PUC'), ('Permit', 'Permit')], max_length=20)),
                ('doc_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_attachment_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_documents',
                'unique_together': {('vehicle', 'doc_type')},
            },
        ),
    ]
