# Generated by Django 5.2.6 on 2026-07-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tyre_changed_odometer_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
