# Generated by Django 5.2.6 on 2026-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_tyre_changed_odometer_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_depot_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
