# Generated by Django 5.2.6 on 2026-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_last_depot_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='account_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
