# Generated by Django 5.2.6 on 2026-07-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_bank_account_number_party_bank_branch_and_more'),
        ('vehicles', '0005_vehicle_fitness_expiry_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avg_mileage_kmpl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed average mileage in km/L (for predictive ROI)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='For Market vehicles: the broker/owner who supplied this truck', limit_choices_to={'party_type': 'Broker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokered_vehicles', to='parties.party'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='broker_tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TDS % to deduct on broker freight payments (typically 1-2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_type',
            field=models.CharField(choices=[('Company', 'Company Owned'), ('Market', 'Market / Hired')], default='Company', max_length=20),
        ),
    ]
