# Generated by Django 5.2.6 on 2026-07-27 13:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_bank_account_number_party_bank_branch_and_more'),
        ('vehicles', '0006_vehicle_avg_mileage_kmpl_vehicle_broker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50)),
                ('name_model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Van', 'Van'), ('Truck', 'Truck'), ('Mini', 'Mini'), ('Bus', 'Bus'), ('Other', 'Other')], default='Van', max_length=20)),
                ('owner_type', models.CharField(choices=[('Company', 'Company Owned'), ('Market', 'Market / Hired')], default='Company', max_length=20)),
                ('broker_tds_rate', models.DecimalField(decimal_places=2, default=0, help_text='TDS % to deduct on broker freight payments (typically 1-2%)', max_digits=5)),
                ('max_load_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tyre_changed_odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rolling_mileage_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_mileage_kmpl', models.DecimalField(blank=True, decimal_places=2, help_text='Computed average mileage in km/L (for predictive ROI)', max_digits=8, null=True)),
                ('tyre_replacement_threshold', models.DecimalField(decimal_places=2, default=40000, max_digits=12)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('permit_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('In Shop', 'In Shop'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('last_depot_return', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('broker', models.ForeignKey(blank=True, db_constraint=False, help_text='For Market vehicles: the broker/owner who supplied this truck', limit_choices_to={'party_type': 'Broker'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parties.party')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle',
                'verbose_name_plural': 'historical vehicles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
