# Generated by Django 5.2.6 on 2026-07-12 05:33

import apps.trips.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(default=apps.trips.models.generate_trip_code, editable=False, max_length=20, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Trip revenue / fee — used for ROI calculation', max_digits=14)),
                ('planned_eta', models.DateTimeField(blank=True, null=True)),
                ('load_type', models.CharField(blank=True, choices=[('Palletized', 'Palletized'), ('Loose', 'Loose'), ('Container', 'Container')], default='', max_length=20)),
                ('freight_type', models.CharField(blank=True, choices=[('FMCG', 'FMCG'), ('Industrial', 'Industrial'), ('Perishable', 'Perishable'), ('Pharmaceutical', 'Pharmaceutical'), ('Automotive', 'Automotive'), ('Other', 'Other')], default='', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('final_odometer_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_consumed_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('home_depot_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
