# Generated by Django 5.2.6 on 2026-07-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='narration',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripLRDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.CharField(max_length=100)),
                ('lr_date', models.DateField(blank=True, null=True)),
                ('consignor', models.CharField(max_length=200)),
                ('consignee', models.CharField(max_length=200)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('goods_description', models.CharField(blank=True, default='', max_length=200)),
                ('loading_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unloading_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('party_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shortage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lr_details', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_lr_details',
            },
        ),
    ]
