# Generated by Django 5.2.6 on 2026-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_arrival_date_trip_arrival_km_trip_narration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='average_kmpl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='run_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
