# Generated by Django 5.2.6 on 2026-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_average_kmpl_trip_departure_km_trip_run_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
