# Generated by Django 5.2.6 on 2026-07-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('trips', '0004_trip_expected_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplrdetail',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='consignee_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee_lrs', to='parties.party'),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='consignor_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignor_lrs', to='parties.party'),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='freight_by',
            field=models.CharField(choices=[('TBB', 'To Be Billed'), ('To Pay', 'To Pay'), ('Paid', 'Paid')], default='TBB', max_length=20),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='triplrdetail',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='triplrdetail',
            name='consignee',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='triplrdetail',
            name='consignor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='FreightInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.party')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='trips.trip')),
            ],
            options={
                'db_table': 'freight_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
